title: Calendar's Blog
description: "A graduate student majoring in computer graphics from Xiamen University."
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: guangzez67@gmaill.com
github_username: Calendar66
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: "Calendar66/Calendar66.github.io"
giscus_repoId: "R_kgDONlocmA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDONlocmM4Cl8UB"
goatcounter_code: calendar
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
  math_engine: mathjax

